#!/usr/bin/env zsh

# vim
alias ni='nvim'
alias vi='vim'
alias nf='nvim $(fzf)'
alias cf='cd $(find * -type d | fzf)'

alias reprofile='source ~/.zshenv; source ~/.config/zsh/.zshrc'
alias _=sudo

# lazygit
alias lg='lazygit'

# matrixorigin
alias kmo='kill -9 $(pgrep -d',' -f mo-service)'

# ranger
# 配置ranger的缩写, 同时使得退出ranger时留在ranger最后的dir的位置
alias ra='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'

# thefuck
alias fk="thefuck"

# python setting
alias pip='pip3'
alias python='python3'

# better tools
alias cat='bat'
