tap "daipeihust/tap"
tap "discoteq/discoteq"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "laishulu/homebrew"
tap "riscv/riscv"
tap "sst/tap"
# Extremely Fast Compression algorithm
brew "lz4"
# General-purpose data compression with high compression ratio
brew "xz"
# Zstandard is a real-time compression algorithm
brew "zstd"
# TIFF library and utilities
brew "libtiff"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Archival front-end
brew "atool"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Real-time data compression library
brew "lzo"
# Vector graphics library with cross-device output support
brew "cairo"
# OpenType text shaping engine
brew "harfbuzz"
# Google's own build tool
brew "bazel"
# User-friendly launcher for Bazel
brew "bazelisk", link: false
# Arbitrary precision numeric processing language
brew "bc"
# Next generation open source RPC library and framework
brew "grpc"
# Generate compilation database for clang tooling
brew "bear"
# Parser generator
brew "bison"
# Collection of portable C++ source libraries
brew "boost"
# GNU multiple precision arithmetic library
brew "gmp"
# Integer Set Library for the polyhedral model
brew "isl"
# C library for multiple-precision floating-point computations
brew "mpfr"
# C library for the arithmetic of high precision complex numbers
brew "libmpc"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Object-file caching compiler wrapper
brew "ccache"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Wrap Gemini CLI, Codex, Claude Code, Qwen Code as an API service
brew "cliproxyapi"
# Statistics utility to count lines of code
brew "cloc"
# Cross-platform make
brew "cmake"
# Console Matrix
brew "cmatrix"
# Wrapper around make to colorize the output
brew "colormake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# C library implementing the SSH2 protocol
brew "libssh2"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Debugger for the Go programming language
brew "delve"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Binary-decimal and decimal-binary routines for IEEE doubles
brew "double-conversion"
# Embeddable SQL OLAP Database Management System
brew "duckdb"
# Text mode web browser
brew "elinks"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# XML 1.0 parser
brew "expat"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Asynchronous event library
brew "libevent"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# Framework for layout and rendering of i18n text
brew "pango"
# Compression/decompression library aiming for high speed
brew "snappy"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Create thumbnails for your video files
brew "ffmpegthumbnailer"
# Fast Lexical Analyzer, generates Scanners (tokenizers)
brew "flex"
# Lock file during command
brew "flock"
# Fast and simple Node.js version manager
brew "fnm"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Graphics library to dynamically manipulate images
brew "gd"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# Library for processing command-line flags
brew "gflags"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Application-level logging library
brew "glog"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Library for USB device access
brew "libusb"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Fast linters runner for Go
brew "golangci-lint"
# Automatically generate Go test boilerplate from your source code
brew "gotests"
# Perfect hash function generator
brew "gperf"
# Image manipulation
brew "netpbm"
# GNU triangulated surface library
brew "gts"
# Library to render SVG files using Cairo
brew "librsvg"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Library for reading RAW files from digital photo cameras
brew "libraw"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Convert pixel information into colored ASCII art
brew "libcaca"
# Shared library for mediainfo
brew "libmediainfo"
# Postgres C API library
brew "libpq"
# General purpose TCP-IP emulator
brew "libslirp"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Next-gen compiler infrastructure
brew "llvm"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Text-based web browser
brew "lynx"
# GUI for vim, made for macOS
brew "macvim"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Unified display of technical and tag data for audio/video
brew "media-info"
# Modern programming language in the Lisp/Scheme family
brew "minimal-racket"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Open source relational database management system
brew "mysql", restart_service: :changed
# Open source relational database management system
brew "mysql-client@8.4"
# Open source relational database management system
brew "mysql@8.4", restart_service: :changed
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Control nvim processes using `nvr` command-line tool
brew "neovim-remote", link: false
# Small build system for use with gyp or CMake
brew "ninja"
# Development kit for the Java programming language
brew "openjdk@11"
# Development kit for the Java programming language
brew "openjdk@17"
# Small collection of programs that operate on patch files
brew "patchutils"
# Highly capable, feature-rich programming language
brew "perl"
# Parallel gzip
brew "pigz"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Protocol buffers (Google's data interchange format)
brew "protobuf@21"
# Generic machine emulator and virtualizer
brew "qemu"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Blazing-fast modern Lua linter
brew "selene"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Fast, configurable, shell plugin manager
brew "sheldon"
# Autoformat shell script source code
brew "shfmt"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# SMART hard drive monitoring
brew "smartmontools"
# SOund eXchange: universal sound sample translator
brew "sox"
# SQL formatter with width-aware output
brew "sqlfmt"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Opinionated Lua code formatter
brew "stylua"
# System performance benchmark tool
brew "sysbench"
# Official documentation format of the GNU project
brew "texinfo"
# Code-search similar to ack
brew "the_silver_searcher"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Lightweight BitTorrent client
brew "transmission-cli"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Pager/text based browser
brew "w3m"
# Internet file retriever
brew "wget"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# Yet Another Dotfiles Manager
brew "yadm"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Switch your input method through terminal
brew "daipeihust/tap/im-select"
# macOS Input Source Manager
brew "laishulu/homebrew/macism"
# RISC-V Compiler GNU Toolchain using newlib
brew "riscv/riscv/riscv-gnu-toolchain"
# RISC-V ISA simulator (spike)
brew "riscv/riscv/riscv-isa-sim"
# RISC-V toolchain including gcc (with newlib), simulator (spike), and pk
brew "riscv/riscv/riscv-tools"
# The AI coding agent built for the terminal.
brew "sst/tap/opencode"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source keystroke visualiser
cask "keycastr"
# Terminal emulator
cask "wave"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Open-source version of the X.Org X Window System
cask "xquartz"
vscode "13xforever.language-x86-64-assembly"
vscode "adpyke.vscode-sql-formatter"
vscode "alefragnani.bookmarks"
vscode "ayanamists.ayaseditor"
vscode "basdp.language-gas-x86"
vscode "charliermarsh.ruff"
vscode "christian-kohler.path-intellisense"
vscode "cschlosser.doxdocgen"
vscode "daohong-emilio.yash"
vscode "davidanson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "dunstontc.vscode-go-syntax"
vscode "eamodio.gitlens"
vscode "fabiospampinato.vscode-diff"
vscode "formulahendry.vscode-mysql"
vscode "foxundermoon.shell-format"
vscode "geddski.macros"
vscode "gimenete.github-linker"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "gruntfuggly.todo-tree"
vscode "hbenl.vscode-test-explorer"
vscode "ibm.output-colorizer"
vscode "jakob101.relativepath"
vscode "jdinhlife.gruvbox"
vscode "johnnymorganz.stylua"
vscode "jscearcy.rust-doc-viewer"
vscode "littlefoxteam.vscode-python-test-adapter"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "mattn.lisp"
vscode "mechatroner.rainbow-csv"
vscode "mkxml.vscode-filesize"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.pylint"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vsliveshare.vsliveshare"
vscode "msyrus.go-doc"
vscode "ohanedan.lowlight-go-errors"
vscode "quillaja.goasm"
vscode "qwenlm.qwen-code-vscode-ide-companion"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "sst-dev.opencode"
vscode "swellaby.rust-pack"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "vscjava.vscode-java-pack"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "wayou.vscode-icons-mac"
vscode "xaver.clang-format"
vscode "yinfei.luahelper"
vscode "yzhang.markdown-all-in-one"
vscode "zhwu95.riscv"
vscode "zxh404.vscode-proto3"
