tap "daipeihust/tap"
tap "discoteq/discoteq"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "riscv/riscv"
# Extremely Fast Compression algorithm
brew "lz4"
# General-purpose data compression with high compression ratio
brew "xz"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Archival front-end
brew "atool"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# User-friendly launcher for Bazel
brew "bazelisk"
# Arbitrary precision numeric processing language
brew "bc"
# Next generation open source RPC library and framework
brew "grpc"
# Generate compilation database for clang tooling
brew "bear"
# Parser generator
brew "bison"
# Collection of portable C++ source libraries
brew "boost"
# GNU multiple precision arithmetic library
brew "gmp"
# Integer Set Library for the polyhedral model
brew "isl"
# C library for multiple-precision floating-point computations
brew "mpfr"
# C library for the arithmetic of high precision complex numbers
brew "libmpc"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Core application library for C
brew "glib"
# Real-time data compression library
brew "lzo"
# Vector graphics library with cross-device output support
brew "cairo"
# Object-file caching compiler wrapper
brew "ccache"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Statistics utility to count lines of code
brew "cloc"
# Cross-platform make
brew "cmake"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Generate a Clang compilation database for Make-based build systems
brew "compiledb"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# C library implementing the SSH2 protocol
brew "libssh2"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Debugger for the Go programming language
brew "delve"
# Binary-decimal and decimal-binary routines for IEEE doubles
brew "double-conversion"
# Text mode web browser
brew "elinks"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# XML 1.0 parser
brew "expat"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Fast Lexical Analyzer, generates Scanners (tokenizers)
brew "flex"
# Lock file during command
brew "flock"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Graphics library to dynamically manipulate images
brew "gd"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# Library for processing command-line flags
brew "gflags"
# Distributed revision control system
brew "git"
# Application-level logging library
brew "glog"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Asynchronous event library
brew "libevent"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Library for USB device access
brew "libusb"
# Fast linters runner for Go
brew "golangci-lint"
# Perfect hash function generator
brew "gperf"
# Image manipulation
brew "netpbm"
# GNU triangulated surface library
brew "gts"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Convert pixel information into colored ASCII art
brew "libcaca"
# Shared library for mediainfo
brew "libmediainfo"
# General purpose TCP-IP emulator
brew "libslirp"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Next-gen compiler infrastructure
brew "llvm"
# Text-based web browser
brew "lynx"
# GUI for vim, made for macOS
brew "macvim"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Unified display of technical and tag data for audio/video
brew "media-info"
# Modern programming language in the Lisp/Scheme family
brew "minimal-racket"
# Protocol buffers (Google's data interchange format)
brew "protobuf@21", link: true
# Open source relational database management system
brew "mysql", restart_service: true
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Control nvim processes using `nvr` command-line tool
brew "neovim-remote", link: false
# Small build system for use with gyp or CMake
brew "ninja"
# Development kit for the Java programming language
brew "openjdk@11"
# Small collection of programs that operate on patch files
brew "patchutils"
# Highly capable, feature-rich programming language
brew "perl"
# Parallel gzip
brew "pigz"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql@14", restart_service: true
# Python interface to Tcl/Tk
brew "python-tk@3.11"
# Compression/decompression library aiming for high speed
brew "snappy"
# Generic machine emulator and virtualizer
brew "qemu"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Autoformat shell script source code
brew "shfmt"
# SQL formatter with width-aware output
brew "sqlfmt"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# System performance benchmark tool
brew "sysbench"
# Official documentation format of the GNU project
brew "texinfo"
# Code-search similar to ack
brew "the_silver_searcher"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Lightweight BitTorrent client
brew "transmission-cli"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Pager/text based browser
brew "w3m"
# Internet file retriever
brew "wget"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# Yet Another Dotfiles Manager
brew "yadm"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Switch your input method through terminal
brew "daipeihust/tap/im-select"
# RISC-V Compiler GNU Toolchain using newlib
brew "riscv/riscv/riscv-gnu-toolchain"
# RISC-V ISA simulator (spike)
brew "riscv/riscv/riscv-isa-sim"
# RISC-V toolchain including gcc (with newlib), simulator (spike), and pk
brew "riscv/riscv/riscv-tools"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source version of the X.Org X Window System
cask "xquartz"
vscode "13xforever.language-x86-64-assembly"
vscode "adpyke.vscode-sql-formatter"
vscode "alefragnani.bookmarks"
vscode "ayanamists.ayaseditor"
vscode "basdp.language-gas-x86"
vscode "bazelbuild.vscode-bazel"
vscode "christian-kohler.path-intellisense"
vscode "cschlosser.doxdocgen"
vscode "daohong-emilio.yash"
vscode "davidanson.vscode-markdownlint"
vscode "deerawan.vscode-dash"
vscode "donjayamanne.githistory"
vscode "dunstontc.vscode-go-syntax"
vscode "eamodio.gitlens"
vscode "evzen-wybitul.magic-racket"
vscode "fabiospampinato.vscode-diff"
vscode "formulahendry.vscode-mysql"
vscode "geddski.macros"
vscode "gimenete.github-linker"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.copilot-labs"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "golang.go-nightly"
vscode "gruntfuggly.todo-tree"
vscode "ibm.output-colorizer"
vscode "jakob101.relativepath"
vscode "jdinhlife.gruvbox"
vscode "jeff-hykin.better-cpp-syntax"
vscode "jscearcy.rust-doc-viewer"
vscode "lishizhen.racket-fmt"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "mattn.lisp"
vscode "mechatroner.rainbow-csv"
vscode "mkxml.vscode-filesize"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.pylint"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "msyrus.go-doc"
vscode "ohanedan.lowlight-go-errors"
vscode "quarto.quarto"
vscode "quillaja.goasm"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "richie5um2.vscode-sort-json"
vscode "rioj7.command-variable"
vscode "rust-lang.rust-analyzer"
vscode "swellaby.rust-pack"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "wayou.vscode-icons-mac"
vscode "wisen.wisen-translate"
vscode "xaver.clang-format"
vscode "yinfei.luahelper"
vscode "yzhang.markdown-all-in-one"
vscode "zhwu95.riscv"
vscode "zxh404.vscode-proto3"
